
CREATE DATABASE If NOT EXISTS user;

use user;

CREATE TABLE IF NOT EXISTS user (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(30) NOT NULL UNIQUE,
email VARCHAR(50) NOT NULL UNIQUE,
pass VARCHAR(255) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS item (
item_id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
item_name VARCHAR(30) NOT NULL,
item_type VARCHAR(8) NOT NULL,
price INT(20) NOT NULL,
available INT(2) NOT NULL,
qty INT(6) NOT NULL,
item_description VARCHAR(255) NOT NULL,
img_name VARCHAR(60) NOT NULL,
sell_type VARCHAR(8) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
userid INT(6) UNSIGNED,
FOREIGN KEY(userid) REFERENCES user(id)
);
CREATE TABLE IF NOT EXISTS customerpost (
item_id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
item_name VARCHAR(30) NOT NULL,
item_type VARCHAR(8) NOT NULL,
price INT(20) NOT NULL,
available INT(2) NOT NULL,
qty INT(6) NOT NULL,
item_description VARCHAR(255) NOT NULL,
img_name VARCHAR(60) NOT NULL,
sell_type VARCHAR(8) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
userid INT(6) UNSIGNED,
FOREIGN KEY(userid) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS admin (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(30) NOT NULL UNIQUE,
email VARCHAR(50) NOT NULL UNIQUE,
pass VARCHAR(255) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sell(
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
item_id INT(6) UNSIGNED,
FOREIGN KEY(item_id) REFERENCES item(item_id),
sell INT(6) UNSIGNED NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS comment(
username VARCHAR(30),
email VARCHAR(50) NOT NULL UNIQUE,
comment VARCHAR(400)
);